SELECT
    "Customer ID" AS customer_id,
    Gender AS gender,
    Age AS age,
    Married AS married,
    "Number of Dependents" AS number_of_dependents,
    City AS city,
    "Zip Code" AS zip_code,
    Latitude AS latitude,
    Longitude AS longitude,
    "Number of Referrals" AS number_of_referrals,
    "Tenure in Months" AS tenure_in_months,
    Offer AS offer,
    "Phone Service" AS phone_service,
    "Avg Monthly Long Distance Charges" AS avg_monthly_long_distance_charges,
    "Multiple Lines" AS multiple_lines,
    "Internet Service" AS internet_service,
    "Internet Type" AS internet_type,
    "Avg Monthly GB Download" AS avg_monthly_gb_download,
    "Online Security" AS online_security,
    "Online Backup" AS online_backup,
    "Device Protection Plan" AS device_protection_plan,
    "Premium Tech Support" AS premium_tech_support,
    "Streaming TV" AS streaming_tv,
    "Streaming Movies" AS streaming_movies,
    "Streaming Music" AS streaming_music,
    "Unlimited Data" AS unlimited_data,
    Contract AS contract,
    "Paperless Billing" AS paperless_billing,
    "Payment Method" AS payment_method,
    "Monthly Charge" AS monthly_charge,
    "Total Charges" AS total_charges,
    "Total Refunds" AS total_refunds,
    "Total Extra Data Charges" AS total_extra_data_charges,
    "Total Long Distance Charges" AS total_long_distance_charges,
    "Total Revenue" AS total_revenue,
    "Customer Status" AS customer_status,
    "Churn Category" AS churn_category,
    "Churn Reason" AS churn_reason
FROM {{ ref('telecom_customer_churn') }}